USE train_project
GO
DROP FUNCTION dbo.ALL_TRAINS;
DROP FUNCTION dbo.GET_TRAINS_FROM_STARTING;
DROP FUNCTION dbo.GET_TRAINS_TO_DESTINATION;
DROP FUNCTION dbo.OTHER_TRAINS;
DROP FUNCTION dbo.DIRECT;
DROP FUNCTION dbo.CALCULATE_TIME;
DROP FUNCTION dbo.ONE_SWITCH;