USE train_project;
GO
--drop all tables

DROP TABLE CARRIAGES_IN_TRAIN;
DROP TABLE PRICING_FOR_CONNECTION;
DROP TABLE CONNECTIONS;
DROP TABLE SEATS;
DROP TABLE TICKETS;
DROP TABLE DISCOUNTS;
DROP TABLE USERS;
DROP TABLE CARRIAGES;
DROP TABLE TRAIN;
DROP TABLE ROUTE_STOPS;
DROP TABLE LOCOMOTIVES;
DROP TABLE ROUTE_WEEKDAYS;
DROP TABLE WEEKDAYS;
DROP TABLE STATION;
DROP TABLE ROUTE_HOLIDAYS;
DROP TABLE HOLIDAYS;
DROP TABLE ROUTE_PRICING;
DROP TABLE PRICING;
DROP TABLE ROUTE;