USE train_project
GO


-- UNWANTED PHENOMENA: TWO PEOPLE BOOK TICKETS FOR THE SAME SEATS
-- ISOLATION LEVEL: THE SAFEST ISOALTION LEVEL IS SERIALIZABLE AS OVERBOOKING COULD LED TO SERIOUS SAFETY VIOLATIONS AND BRAND DEMAGE
/*
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
*/
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

BEGIN TRANSACTION;

INSERT INTO TICKETS (total_price, payment_method, discount_id, users_id) 
VALUES (150.50, 'credit card', 3, 1);

DECLARE @NewTicketID INT = SCOPE_IDENTITY();
    
IF NOT EXISTS (
    SELECT * FROM CONNECTIONS 
    WHERE seat_number = 5 AND carriage_id = 1 AND train_id = 1
)

BEGIN
    WAITFOR DELAY '00:00:05';
    INSERT INTO CONNECTIONS (ticket_id, connection_order, price, carriage_id, seat_number, train_id, route_id, starting_order, destination_order) 
    VALUES (@NewTicketID, 1, 150.50, 1, 5, 1, 'IC2810', 1, 3);
    INSERT INTO PRICING_FOR_CONNECTION (pricing_id, ticket_id, connection_order) VALUES
    (4, @NewTicketID, 1);
    COMMIT TRANSACTION;
END
ELSE
    BEGIN
    ROLLBACK TRANSACTION;
    PRINT('rolled back');
    END
   

SELECT * FROM CONNECTIONS WHERE seat_number = 5 AND carriage_id =1 AND train_id = 1
SELECT* FROM TICKETS 
