USE train_project
GO

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

BEGIN TRANSACTION;

DECLARE @TargetPricingID INT = ( SELECT pricing_id 
FROM PRICING 
WHERE from_km = 0 
  AND to_km = 400 
  AND class = 1 
  AND price_for_km = 0.2);


IF @TargetPricingID IS NULL
BEGIN
    WAITFOR DELAY '00:00:05';
    INSERT INTO PRICING (price_for_km, class, from_km, to_km)
    VALUES (0.2, 1, 0, 400);
    
    SET @TargetPricingID = SCOPE_IDENTITY();
    PRINT('new pricing added');
    
END

INSERT INTO ROUTE_PRICING (route_id, pricing_id) VALUES
    ('IC2810', @TargetPricingID)


COMMIT TRANSACTION;

SELECT * FROM ROUTE_PRICING
SELECT * FROM PRICING
--WITHOUT PROPER ISOLATION, WHEN TWO USERS SIMOULTANOUSLY CHECK FOR THE PRICING AND DONT FIND APPROPRAITE ONE THERE ARE REDUNDANT ENTRIES IN THE DB CREATED
--THIS CAN CREATE ERRORS AND IS GENERALY A BAD PRACTICE